"""temp_check

Revision ID: 06d506fe6e98
Revises: a1aa676a6332
Create Date: 2025-07-11 14:22:13.486787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d506fe6e98'
down_revision = 'a1aa676a6332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jumps', sa.Column('reserved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jumps', 'reserved')
    # ### end Alembic commands ###
