"""temp_check

Revision ID: 072a0d5bc3bc
Revises: 06d506fe6e98
Create Date: 2025-07-14 15:03:18.035693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072a0d5bc3bc'
down_revision = '06d506fe6e98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('aircraft', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aircraft', 'users', ['deleted_by'], ['id'])
    op.add_column('jump_types', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jump_types', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jump_types', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jump_types', type_='foreignkey')
    op.drop_column('jump_types', 'deleted_by')
    op.drop_column('jump_types', 'deleted_at')
    op.drop_constraint(None, 'aircraft', type_='foreignkey')
    op.drop_column('aircraft', 'deleted_by')
    op.drop_column('aircraft', 'deleted_at')
    # ### end Alembic commands ###
