"""temp_check

Revision ID: 0fef88e00322
Revises: bdd659345f20
Create Date: 2025-07-15 16:22:41.624269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fef88e00322'
down_revision = 'bdd659345f20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('telegram_data', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_tokens_id'), 'temporary_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_temporary_tokens_telegram_id'), 'temporary_tokens', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_temporary_tokens_token'), 'temporary_tokens', ['token'], unique=True)
    op.add_column('users', sa.Column('registration_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_completed')
    op.drop_index(op.f('ix_temporary_tokens_token'), table_name='temporary_tokens')
    op.drop_index(op.f('ix_temporary_tokens_telegram_id'), table_name='temporary_tokens')
    op.drop_index(op.f('ix_temporary_tokens_id'), table_name='temporary_tokens')
    op.drop_table('temporary_tokens')
    # ### end Alembic commands ###
