"""temp_check

Revision ID: 2cb397010f36
Revises: c00a42d34b73
Create Date: 2025-07-16 09:53:45.971713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb397010f36'
down_revision = 'c00a42d34b73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jumps', sa.Column('staff_assignments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jumps', 'staff_assignments')
    # ### end Alembic commands ###
