"""temp_check

Revision ID: 37fe7b885e22
Revises: 072a0d5bc3bc
Create Date: 2025-07-14 19:41:46.288523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fe7b885e22'
down_revision = '072a0d5bc3bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jumps', sa.Column('jump_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jumps', 'jump_date')
    # ### end Alembic commands ###
