"""temp_check

Revision ID: 436144577cf7
Revises: 60ace25c31f6
Create Date: 2025-07-08 13:03:38.332523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436144577cf7'
down_revision = '60ace25c31f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_test_field', sa.String(), nullable=True))
    op.drop_column('users', 'test_migration_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_migration_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'new_test_field')
    # ### end Alembic commands ###
