"""temp_check

Revision ID: 5033949a58c5
Revises: ffb9ab1ff07e
Create Date: 2025-07-10 11:43:50.221939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5033949a58c5'
down_revision = 'ffb9ab1ff07e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_document_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('license_document_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
