"""Test migration for new field

Revision ID: 60ace25c31f6
Revises: 9d4e7f5c12ab
Create Date: 2025-07-08 12:59:35.166717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ace25c31f6'
down_revision = '9d4e7f5c12ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dictionaries_id'), 'dictionaries', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_values_id'), 'dictionary_values', ['id'], unique=False)
    op.drop_constraint('dictionary_values_dictionary_id_fkey', 'dictionary_values', type_='foreignkey')
    op.create_foreign_key(None, 'dictionary_values', 'dictionaries', ['dictionary_id'], ['id'])
    op.create_foreign_key(None, 'equipment', 'dictionary_values', ['name_id'], ['id'])
    op.create_foreign_key(None, 'equipment', 'dictionary_values', ['type_id'], ['id'])
    op.create_foreign_key(None, 'equipment', 'dictionary_values', ['status_id'], ['id'])
    op.create_foreign_key(None, 'jumps', 'dictionary_values', ['jump_type_id'], ['id'])
    op.create_foreign_key(None, 'jumps', 'dictionary_values', ['payment_status_id'], ['id'])
    op.create_foreign_key(None, 'loads', 'dictionary_values', ['status_id'], ['id'])
    op.create_foreign_key(None, 'manifests', 'dictionary_values', ['jump_type_id'], ['id'])
    op.add_column('users', sa.Column('test_migration_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_migration_field')
    op.drop_constraint(None, 'manifests', type_='foreignkey')
    op.drop_constraint(None, 'loads', type_='foreignkey')
    op.drop_constraint(None, 'jumps', type_='foreignkey')
    op.drop_constraint(None, 'jumps', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'dictionary_values', type_='foreignkey')
    op.create_foreign_key('dictionary_values_dictionary_id_fkey', 'dictionary_values', 'dictionaries', ['dictionary_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_dictionary_values_id'), table_name='dictionary_values')
    op.drop_index(op.f('ix_dictionaries_id'), table_name='dictionaries')
    # ### end Alembic commands ###
