"""Initial migration

Revision ID: 8b9aa81ebb08
Revises: 2e3df3dd93dd
Create Date: 2025-06-26 17:58:06.092435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9aa81ebb08'
down_revision = '2e3df3dd93dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
