"""temp_check

Revision ID: 8edff6f0f89b
Revises: 436144577cf7
Create Date: 2025-07-08 13:07:02.273970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edff6f0f89b'
down_revision = '436144577cf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
