"""temp_check

Revision ID: bdd659345f20
Revises: 37fe7b885e22
Create Date: 2025-07-14 19:56:04.201131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd659345f20'
down_revision = '37fe7b885e22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('users', sa.Column('starting_number_of_jumps', sa.Integer(), nullable=True))
    
    # Update existing records to have default value of 0
    op.execute("UPDATE users SET starting_number_of_jumps = 0 WHERE starting_number_of_jumps IS NULL")
    
    # Now alter the column to be NOT NULL
    op.alter_column('users', 'starting_number_of_jumps', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'starting_number_of_jumps')
    # ### end Alembic commands ###
