"""temp_check

Revision ID: c00a42d34b73
Revises: 0fef88e00322
Create Date: 2025-07-15 16:36:24.579324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00a42d34b73'
down_revision = '0fef88e00322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_completed')
    # ### end Alembic commands ###
