"""temp_check

Revision ID: cb5feac855cf
Revises: 165c5faf574f
Create Date: 2025-07-11 08:42:44.795037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5feac855cf'
down_revision = '165c5faf574f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PLANE', 'HELI', name='aircrafttype'), nullable=False),
    sa.Column('max_load', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_id'), 'aircraft', ['id'], unique=False)
    op.create_table('loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('FORMING', 'ON_CALL', 'DEPARTED', name='loadstatus'), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('reserved_spaces', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('reserved_spaces >= 0', name='reserved_spaces_non_negative'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_id'), 'loads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loads_id'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_aircraft_id'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
